- hosts: pg-for-kafka
  remote_user:
    root
  vars:
    kernel_pid_max: 196608
    nproc: 196600
    username: rpasvnp
    
  tasks:
  - name: Set kernel.pid_max 
    ansible.posix.sysctl:
      name: kernel.pid_max
      value: '{{  kernel_pid_max  }}'
      sysctl_set: yes

  - name: Ensure the kernel.pid_max is ok in /etc/sysctl.d/pid_max.conf
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/pid_max.conf
      regexp: '^kernel.pid_max '
      line: kernel.pid_max={{  kernel_pid_max  }}
      create: yes

  - name: Ensure the limits is ok in file /etc/security/limits.conf
    ansible.builtin.lineinfile:
      path: /etc/security/limits.conf
      regexp: '^{{  username  }} hard nproc'
      line: '{{  username  }} hard nproc {{  nproc  }}'
      create: yes      

  - name: Ensure the limits is ok in file /etc/security/limits.conf
    ansible.builtin.lineinfile:
      path: /etc/security/limits.conf
      regexp: '^{{  username  }} soft nproc'
      line: '{{  username  }} soft nproc {{  nproc  }}'
      create: yes      

